### ISSUE TITLE
Converging issues

### ISSUE THREAD

**Issue by iennae** [mhedgpeth/cafe-cookbook#8]
Hey @mhedgpeth 

I'm attempting to test this cookbook out and getting a failure to converge. I set up a local kitchen.yml and using the Chef standard windows image so might be something about our image.

 Recipe: <Dynamically Defined Resource>
           * remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\package\vc_redist.x86.exe] action create
             - create new file C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\package\vc_redist.x86.exe
             - update content in file C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\package\vc_redist.x86.exe from none to 12a69a
             (file sizes exceed 10000000 bytes, diff output suppressed)

           ================================================================================
           Error executing action `install` on resource 'windows_package[Microsoft Visual C++ 2015 x86 Additional Runtime - 14.0.24215]'          ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '5'
           ---- Begin output of start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\vc_redist.x86.exe"   /q & exit %%%%ERRORLEVEL%%%% ----
           STDOUT:
           STDERR:
           ---- End output of start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\vc_redist.x86.exe"   /q & exit %%%%ERRORLEVEL%%%% ----
           Ran start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\vc_redist.x86.exe"   /q & exit %%%%ERRORLEVEL%%%% returned 5

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/vcruntime/recipes/vc14.rb

            30:     package node['vcruntime']['vc14']['x86'][node['vcruntime']['vc14']['version']]['name'] do
            31:       checksum node['vcruntime']['vc14']['x86'][node['vcruntime']['vc14']['version']]['sha256sum']
            32:       source node['vcruntime']['vc14']['x86'][node['vcruntime']['vc14']['version']]['url']
            33:       installer_type :custom
            34:       options '/q'
            35:     end
            36:   when /i[3-6]86/

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/vcruntime/recipes/vc14.rb:30:in `from
           ================================================================================

I haven't dug into this a lot, but if you have any thoughts about what needs to be done to make this work, let me know :) Thanks!

**Comment by mhedgpeth** [comment]
hey @iennae thanks so much for your feedback and help with this cookbook. I didn't know there was a chef standard windows image. Do I have access to that? I could try testing it with Matt Wrock's image if that would help. I've been testing kitchen with the azure provider and that works well.

To translate your error message to English, the `vcruntime` cookbook installs the VC Redistributable package which is a prerequisite to running `dotnet` core on that machine. The install of this package is failing for some reason on your image. If I had access to the image, I'd reproduce, then try to just RDP into the machine with the `vagrant` user and run that manually and see what error message I got. I can do that for you if you get me access to that image you're using. Let me know what works best for you.

**Comment by iennae** [comment]
The Chef standard windows image is locked down due to licensing issues. i don't have an azure account. I think Matt's might work? I think the azure testing is great, because other folks who have it it's useful.

**Comment by iennae** [comment]
Hmm. So I've gotten to a different point now:

ipe: cafe::default
         * directory[cafe cache directory] action create (up to date)
         * remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache/cafe/cafe-win8-x64-0.5.4.0.zip] action create (up to date)
         * remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache/cafe/cafe-win8-x64-0.5.4.0.zip] action create (up to date)
         * windows_service[stop cafe] action nothing (skipped due to action :nothing)
         * directory[C:/cafe] action create (up to date)
         * windows_zipfile[unzip cafe] action nothing (skipped due to action :nothing)
         * execute[initialize cafe] action nothing (skipped due to action :nothing)
         * execute[register cafe] action nothing (skipped due to action :nothing)
         * template[C:/cafe/server.json] action create
           - update content in file C:/cafe/server.json from 85542f to 5cfd19
           --- C:/cafe/server.json	2017-04-29 19:22:49.000000000 -0700
           +++ C:/cafe/chef-server20170501-2840-15u120y.json	2017-05-01 16:55:03.000000000 -0700
           @@ -1,5 +1,5 @@
            {
           -    "ChefInterval": 0,
           +    "ChefInterval": 1800,
         "Port": 59320,
         "InstallRoot": "C:"
            }
         * windows_service[cafe] action restart

           ================================================================================
           Error executing action `restart` on resource 'windows_service[cafe]'
           ================================================================================

           SystemCallError
           ---------------
           The specified service does not exist as an installed service. - OpenService: The specified service does not exist as an installed service.

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/cafe/recipes/default.rb

            82: service 'cafe' do
            83:   action :start
            84: end

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/cafe/recipes/default.rb:82:in `from_file'

           windows_service("cafe") do
             action [:start]
             default_guard_interpreter :default
             service_name "cafe"
             enabled nil
             running nil
             masked nil
             pattern "cafe"
             startup_type :automatic
             declared_type :service
             cookbook_name "cafe"
             recipe_name "default"
           end

           System Info:
           ------------
           chef_version=13.0.118
           platform=windows
           platform_version=6.3.9600
           ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
           program_name=C:/opscode/chef/bin/chef-client

I don't think I did anything different other than re-converge for the third time. I've destroyed the image and trying to reconverge to see if I get back the original error. It might be a length of time to install the package?

**Comment by iennae** [comment]
It's definitely back :)

<details>
       Running handlers:
       [2017-05-01T16:59:39-07:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-05-01T16:59:39-07:00] ERROR: Exception handlers complete
       Chef Client failed. 1 resources updated in 11 seconds
       [2017-05-01T16:59:39-07:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2017-05-01T16:59:39-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-05-01T16:59:39-07:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: windows_package[Microsoft Visual C++ 2015 x64 Additional Runtime - 14.0.24215] (vcruntime::vc14 line 24) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '5'
       ---- Begin output of start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\vc_redist.x64.exe"   /q & exit %%%%ERRORLEVEL%%%% ----
       STDOUT:
       STDERR:
       ---- End output of start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\vc_redist.x64.exe"   /q & exit %%%%ERRORLEVEL%%%% ----
       Ran start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\vc_redist.x64.exe"   /q & exit %%%%ERRORLEVEL%%%% returned 5
</details>

**Comment by iennae** [comment]
So it's apparently a timing issue. If I wait longer it will converge and then complain on the windows service.

**Comment by mhedgpeth** [comment]
thanks again for your help with this @iennae. This afternoon I'm going to release cafe 0.8.0 which has a better updating logic. I'll then test this cookbook out with that version to make sure everything works. I've added some changes and will merge them shortly as well and have converged the cookbook with my azure driver.

The challenge I'm having is that cafe is meant to control chef, so the `chef_zero` driver will get short-circuited if I try to test out this cookbook it totality. I'm wondering if ideally I should write a cafe provisioner for kitchen so I can test that it can update chef well. I'll have to think that through a bit more.

Thanks for your help! It has been a pleasant surprise and a wonderful motivator for me. :)

**Comment by mhedgpeth** [comment]
@iennae it should converge now. Please reopen if you see anything with the new version. Thanks again for your help!
